package net.f1la.talesofskyrim.item;

import net.f1la.talesofskyrim.TalesOfSkyrimMod;
import net.f1la.talesofskyrim.block.ModBlocks;
import net.minecraft.core.registries.Registries;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceKey;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.ItemStack;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.RegistryObject;

public class ModCreativeModeTabs {
    public static final DeferredRegister<CreativeModeTab> CREATIVE_MODE_TABS =
            DeferredRegister.create(Registries.CREATIVE_MODE_TAB, TalesOfSkyrimMod.MOD_ID);

    public static final RegistryObject<CreativeModeTab> GENERAL_TAB = CREATIVE_MODE_TABS.register("general_tab",
            () -> {
                CreativeModeTab.Builder builder = CreativeModeTab.builder();
                builder.icon(() -> new ItemStack(ModItems.STEEL_HELMET.get()));
                builder.title(Component.translatable("creativetab.general_tab"));
                builder.displayItems((displayParameters, output) -> {
                    output.accept(ModBlocks.AMETHYST_ORE.get());
                    output.accept(ModBlocks.DEEPSLATE_AMETHYST_ORE.get());
                    output.accept(ModBlocks.GARNET_ORE.get());
                    output.accept(ModBlocks.DEEPSLATE_GARNET_ORE.get());
                    output.accept(ModBlocks.RUBY_ORE.get());
                    output.accept(ModBlocks.DEEPSLATE_RUBY_ORE.get());
                    output.accept(ModBlocks.SAPPHIRE_ORE.get());
                    output.accept(ModBlocks.DEEPSLATE_SAPPHIRE_ORE.get());
                    output.accept(ModBlocks.CORUNDUM_ORE.get());
                    output.accept(ModBlocks.DEEPSLATE_CORUNDUM_ORE.get());
                    output.accept(ModBlocks.SILVER_ORE.get());
                    output.accept(ModBlocks.DEEPSLATE_SILVER_ORE.get());
                    output.accept(ModBlocks.ORICHALCUM_ORE.get());
                    output.accept(ModBlocks.DEEPSLATE_ORICHALCUM_ORE.get());
                    output.accept(ModBlocks.MOONSTONE_ORE.get());
                    output.accept(ModBlocks.DEEPSLATE_MOONSTONE_ORE.get());
                    output.accept(ModBlocks.MALACHITE_ORE.get());
                    output.accept(ModBlocks.DEEPSLATE_MALACHITE_ORE.get());
                    output.accept(ModBlocks.EBONY_ORE.get());
                    output.accept(ModBlocks.DEEPSLATE_EBONY_ORE.get());
                    output.accept(ModBlocks.AMETHYST_BLOCK.get());
                    output.accept(ModBlocks.GARNET_BLOCK.get());
                    output.accept(ModBlocks.RUBY_BLOCK.get());
                    output.accept(ModBlocks.SAPPHIRE_BLOCK.get());
                    output.accept(ModBlocks.STEEL_BLOCK.get());
                    output.accept(ModBlocks.SILVER_BLOCK.get());
                    output.accept(ModBlocks.ORICHALCUM_BLOCK.get());
                    output.accept(ModBlocks.MOONSTONE_BLOCK.get());
                    output.accept(ModBlocks.MALACHITE_BLOCK.get());
                    output.accept(ModBlocks.EBONY_BLOCK.get());
                    output.accept(ModBlocks.DWARVEN_BLOCK.get());
                    output.accept(ModItems.RAW_CORUNDUM.get());
                    output.accept(ModItems.RAW_SILVER.get());
                    output.accept(ModItems.RAW_ORICHALCUM.get());
                    output.accept(ModItems.RAW_MOONSTONE.get());
                    output.accept(ModItems.RAW_MALACHITE.get());
                    output.accept(ModItems.RAW_EBONY.get());
                    output.accept(ModItems.CORUNDUM_NUGGET.get());
                    output.accept(ModItems.DWARVEN_NUGGET.get());
                    output.accept(ModItems.STEEL_NUGGET.get());
                    output.accept(ModItems.SILVER_NUGGET.get());
                    output.accept(ModItems.ORICHALCUM_NUGGET.get());
                    output.accept(ModItems.MOONSTONE_NUGGET.get());
                    output.accept(ModItems.MALACHITE_NUGGET.get());
                    output.accept(ModItems.EBONY_NUGGET.get());
                    output.accept(ModItems.AMETHYST.get());
                    output.accept(ModItems.GARNET.get());
                    output.accept(ModItems.RUBY.get());
                    output.accept(ModItems.SAPPHIRE.get());
                    output.accept(ModItems.CORUNDUM_INGOT.get());
                    output.accept(ModItems.DWARVEN_INGOT.get());
                    output.accept(ModItems.STEEL_INGOT.get());
                    output.accept(ModItems.SILVER_INGOT.get());
                    output.accept(ModItems.ORICHALCUM_INGOT.get());
                    output.accept(ModItems.MOONSTONE_INGOT.get());
                    output.accept(ModItems.MALACHITE_INGOT.get());
                    output.accept(ModItems.EBONY_INGOT.get());
                    output.accept(ModItems.DAEDRA_HEART.get());
                    output.accept(ModItems.DRAGON_BONE.get());
                    output.accept(ModItems.DRAGON_SCALES.get());
                    output.accept(ModItems.STEEL_SHOVEL.get());
                    output.accept(ModItems.STEEL_PICKAXE.get());
                    output.accept(ModItems.STEEL_AXE.get());
                    output.accept(ModItems.STEEL_HOE.get());
                    output.accept(ModItems.STEEL_HELMET.get());
                    output.accept(ModItems.STEEL_CHESTPLATE.get());
                    output.accept(ModItems.STEEL_LEGGINGS.get());
                    output.accept(ModItems.STEEL_BOOTS.get());
                    output.accept(ModItems.STEEL_SWORD.get());
                    output.accept(ModItems.STEEL_DAGGER.get());
                    output.accept(ModItems.STEEL_MACE.get());
                    output.accept(ModItems.STEEL_BOW.get());
                    output.accept(ModItems.SILVER_SHOVEL.get());
                    output.accept(ModItems.SILVER_PICKAXE.get());
                    output.accept(ModItems.SILVER_AXE.get());
                    output.accept(ModItems.SILVER_HOE.get());
                    //output.accept(ModItems.SILVER_HELMET.get());
                    //output.accept(ModItems.SILVER_CHESTPLATE.get());
                    //output.accept(ModItems.SILVER_LEGGINGS.get());
                    //output.accept(ModItems.SILVER_BOOTS.get());
                    output.accept(ModItems.SILVER_SWORD.get());
                    output.accept(ModItems.SILVER_DAGGER.get());
                    output.accept(ModItems.SILVER_MACE.get());
                    output.accept(ModItems.SILVER_BOW.get());
                    output.accept(ModItems.MOONSTONE_SHOVEL.get());
                    output.accept(ModItems.MOONSTONE_PICKAXE.get());
                    output.accept(ModItems.MOONSTONE_AXE.get());
                    output.accept(ModItems.MOONSTONE_HOE.get());
                    output.accept(ModItems.MOONSTONE_HELMET.get());
                    output.accept(ModItems.MOONSTONE_CHESTPLATE.get());
                    output.accept(ModItems.MOONSTONE_LEGGINGS.get());
                    output.accept(ModItems.MOONSTONE_BOOTS.get());
                    output.accept(ModItems.MOONSTONE_SWORD.get());
                    output.accept(ModItems.MOONSTONE_DAGGER.get());
                    output.accept(ModItems.MOONSTONE_MACE.get());
                    output.accept(ModItems.MOONSTONE_BOW.get());
                    output.accept(ModItems.DWARVEN_SHOVEL.get());
                    output.accept(ModItems.DWARVEN_PICKAXE.get());
                    output.accept(ModItems.DWARVEN_AXE.get());
                    output.accept(ModItems.DWARVEN_HOE.get());
                    output.accept(ModItems.DWARVEN_HELMET.get());
                    output.accept(ModItems.DWARVEN_CHESTPLATE.get());
                    output.accept(ModItems.DWARVEN_LEGGINGS.get());
                    output.accept(ModItems.DWARVEN_BOOTS.get());
                    output.accept(ModItems.DWARVEN_SWORD.get());
                    output.accept(ModItems.DWARVEN_DAGGER.get());
                    output.accept(ModItems.DWARVEN_MACE.get());
                    output.accept(ModItems.DWARVEN_BOW.get());
                    output.accept(ModItems.ORICHALCUM_SHOVEL.get());
                    output.accept(ModItems.ORICHALCUM_PICKAXE.get());
                    output.accept(ModItems.ORICHALCUM_AXE.get());
                    output.accept(ModItems.ORICHALCUM_HOE.get());
                    output.accept(ModItems.ORICHALCUM_HELMET.get());
                    output.accept(ModItems.ORICHALCUM_CHESTPLATE.get());
                    output.accept(ModItems.ORICHALCUM_LEGGINGS.get());
                    output.accept(ModItems.ORICHALCUM_BOOTS.get());
                    output.accept(ModItems.ORICHALCUM_SWORD.get());
                    output.accept(ModItems.ORICHALCUM_DAGGER.get());
                    output.accept(ModItems.ORICHALCUM_MACE.get());
                    output.accept(ModItems.ORICHALCUM_BOW.get());
                    output.accept(ModItems.MALACHITE_SHOVEL.get());
                    output.accept(ModItems.MALACHITE_PICKAXE.get());
                    output.accept(ModItems.MALACHITE_AXE.get());
                    output.accept(ModItems.MALACHITE_HOE.get());
                    output.accept(ModItems.MALACHITE_HELMET.get());
                    output.accept(ModItems.MALACHITE_CHESTPLATE.get());
                    output.accept(ModItems.MALACHITE_LEGGINGS.get());
                    output.accept(ModItems.MALACHITE_BOOTS.get());
                    output.accept(ModItems.MALACHITE_SWORD.get());
                    output.accept(ModItems.MALACHITE_DAGGER.get());
                    output.accept(ModItems.MALACHITE_MACE.get());
                    output.accept(ModItems.MALACHITE_BOW.get());
                    output.accept(ModItems.EBONY_SHOVEL.get());
                    output.accept(ModItems.EBONY_PICKAXE.get());
                    output.accept(ModItems.EBONY_AXE.get());
                    output.accept(ModItems.EBONY_HOE.get());
                    output.accept(ModItems.EBONY_HELMET.get());
                    output.accept(ModItems.EBONY_CHESTPLATE.get());
                    output.accept(ModItems.EBONY_LEGGINGS.get());
                    output.accept(ModItems.EBONY_BOOTS.get());
                    output.accept(ModItems.EBONY_SWORD.get());
                    output.accept(ModItems.EBONY_DAGGER.get());
                    output.accept(ModItems.EBONY_MACE.get());
                    output.accept(ModItems.EBONY_BOW.get());
                    output.accept(ModItems.DAEDRIC_SHOVEL.get());
                    output.accept(ModItems.DAEDRIC_PICKAXE.get());
                    output.accept(ModItems.DAEDRIC_AXE.get());
                    output.accept(ModItems.DAEDRIC_HOE.get());
                    output.accept(ModItems.DAEDRIC_HELMET.get());
                    output.accept(ModItems.DAEDRIC_CHESTPLATE.get());
                    output.accept(ModItems.DAEDRIC_LEGGINGS.get());
                    output.accept(ModItems.DAEDRIC_BOOTS.get());
                    output.accept(ModItems.DAEDRIC_SWORD.get());
                    output.accept(ModItems.DAEDRIC_DAGGER.get());
                    output.accept(ModItems.DAEDRIC_MACE.get());
                    output.accept(ModItems.DAEDRIC_BOW.get());
                    output.accept(ModItems.DRAGON_SHOVEL.get());
                    output.accept(ModItems.DRAGON_PICKAXE.get());
                    output.accept(ModItems.DRAGON_AXE.get());
                    output.accept(ModItems.DRAGON_HOE.get());
                    output.accept(ModItems.DRAGON_HELMET.get());
                    output.accept(ModItems.DRAGON_CHESTPLATE.get());
                    output.accept(ModItems.DRAGON_LEGGINGS.get());
                    output.accept(ModItems.DRAGON_BOOTS.get());
                    output.accept(ModItems.DRAGON_SWORD.get());
                    output.accept(ModItems.DRAGON_DAGGER.get());
                    output.accept(ModItems.DRAGON_MACE.get());
                    output.accept(ModItems.DRAGON_BOW.get());

                });
                return builder.build();
            });


    public static void register(IEventBus eventBus) {
        CREATIVE_MODE_TABS.register(eventBus);
    }
}
