package com.ombremoon.talesofskyrim.common.init;

import com.ombremoon.talesofskyrim.common.init.item.ItemInit;
import com.ombremoon.talesofskyrim.Constants;
import com.ombremoon.talesofskyrim.common.init.block.BlockInit;
import net.minecraft.core.registries.Registries;
import net.minecraft.network.chat.Component;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.ItemStack;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.RegistryObject;

public class ModCreativeModeTabs {
    public static final DeferredRegister<CreativeModeTab> CREATIVE_MODE_TABS =
            DeferredRegister.create(Registries.CREATIVE_MODE_TAB, Constants.MOD_ID);

    public static final RegistryObject<CreativeModeTab> GENERAL_TAB = CREATIVE_MODE_TABS.register("general_tab",
            () -> {
                CreativeModeTab.Builder builder = CreativeModeTab.builder();
                builder.icon(() -> new ItemStack(ItemInit.STEEL_HELMET.get()));
                builder.title(Component.translatable("creativetab.general_tab"));
                builder.displayItems((displayParameters, output) -> {
                    output.accept(BlockInit.AMETHYST_ORE.get());
                    output.accept(BlockInit.DEEPSLATE_AMETHYST_ORE.get());
                    output.accept(BlockInit.GARNET_ORE.get());
                    output.accept(BlockInit.DEEPSLATE_GARNET_ORE.get());
                    output.accept(BlockInit.RUBY_ORE.get());
                    output.accept(BlockInit.DEEPSLATE_RUBY_ORE.get());
                    output.accept(BlockInit.SAPPHIRE_ORE.get());
                    output.accept(BlockInit.DEEPSLATE_SAPPHIRE_ORE.get());
                    output.accept(BlockInit.CORUNDUM_ORE.get());
                    output.accept(BlockInit.DEEPSLATE_CORUNDUM_ORE.get());
                    output.accept(BlockInit.SILVER_ORE.get());
                    output.accept(BlockInit.DEEPSLATE_SILVER_ORE.get());
                    output.accept(BlockInit.ORICHALCUM_ORE.get());
                    output.accept(BlockInit.DEEPSLATE_ORICHALCUM_ORE.get());
                    output.accept(BlockInit.MOONSTONE_ORE.get());
                    output.accept(BlockInit.DEEPSLATE_MOONSTONE_ORE.get());
                    output.accept(BlockInit.MALACHITE_ORE.get());
                    output.accept(BlockInit.DEEPSLATE_MALACHITE_ORE.get());
                    output.accept(BlockInit.EBONY_ORE.get());
                    output.accept(BlockInit.DEEPSLATE_EBONY_ORE.get());
                    output.accept(BlockInit.AMETHYST_BLOCK.get());
                    output.accept(BlockInit.GARNET_BLOCK.get());
                    output.accept(BlockInit.RUBY_BLOCK.get());
                    output.accept(BlockInit.SAPPHIRE_BLOCK.get());
                    output.accept(BlockInit.STEEL_BLOCK.get());
                    output.accept(BlockInit.SILVER_BLOCK.get());
                    output.accept(BlockInit.ORICHALCUM_BLOCK.get());
                    output.accept(BlockInit.MOONSTONE_BLOCK.get());
                    output.accept(BlockInit.MALACHITE_BLOCK.get());
                    output.accept(BlockInit.EBONY_BLOCK.get());
                    output.accept(BlockInit.DWARVEN_BLOCK.get());
                    output.accept(ItemInit.RAW_CORUNDUM.get());
                    output.accept(ItemInit.RAW_SILVER.get());
                    output.accept(ItemInit.RAW_ORICHALCUM.get());
                    output.accept(ItemInit.RAW_MOONSTONE.get());
                    output.accept(ItemInit.RAW_MALACHITE.get());
                    output.accept(ItemInit.RAW_EBONY.get());
                    output.accept(ItemInit.CORUNDUM_NUGGET.get());
                    output.accept(ItemInit.DWARVEN_NUGGET.get());
                    output.accept(ItemInit.STEEL_NUGGET.get());
                    output.accept(ItemInit.SILVER_NUGGET.get());
                    output.accept(ItemInit.ORICHALCUM_NUGGET.get());
                    output.accept(ItemInit.MOONSTONE_NUGGET.get());
                    output.accept(ItemInit.MALACHITE_NUGGET.get());
                    output.accept(ItemInit.EBONY_NUGGET.get());
                    output.accept(ItemInit.AMETHYST.get());
                    output.accept(ItemInit.GARNET.get());
                    output.accept(ItemInit.RUBY.get());
                    output.accept(ItemInit.SAPPHIRE.get());
                    output.accept(ItemInit.CORUNDUM_INGOT.get());
                    output.accept(ItemInit.DWARVEN_INGOT.get());
                    output.accept(ItemInit.STEEL_INGOT.get());
                    output.accept(ItemInit.SILVER_INGOT.get());
                    output.accept(ItemInit.ORICHALCUM_INGOT.get());
                    output.accept(ItemInit.MOONSTONE_INGOT.get());
                    output.accept(ItemInit.MALACHITE_INGOT.get());
                    output.accept(ItemInit.EBONY_INGOT.get());
                    output.accept(ItemInit.DAEDRA_HEART.get());
                    output.accept(ItemInit.DRAGON_BONE.get());
                    output.accept(ItemInit.DRAGON_SCALES.get());
                    output.accept(ItemInit.STEEL_SHOVEL.get());
                    output.accept(ItemInit.STEEL_PICKAXE.get());
                    output.accept(ItemInit.STEEL_AXE.get());
                    output.accept(ItemInit.STEEL_HOE.get());
                    output.accept(ItemInit.STEEL_HELMET.get());
                    output.accept(ItemInit.STEEL_CHESTPLATE.get());
                    output.accept(ItemInit.STEEL_LEGGINGS.get());
                    output.accept(ItemInit.STEEL_BOOTS.get());
                    output.accept(ItemInit.STEEL_SWORD.get());
                    output.accept(ItemInit.STEEL_DAGGER.get());
                    output.accept(ItemInit.STEEL_MACE.get());
                    output.accept(ItemInit.STEEL_BOW.get());
                    output.accept(ItemInit.SILVER_SHOVEL.get());
                    output.accept(ItemInit.SILVER_PICKAXE.get());
                    output.accept(ItemInit.SILVER_AXE.get());
                    output.accept(ItemInit.SILVER_HOE.get());
                    //output.accept(ModItems.SILVER_HELMET.get());
                    //output.accept(ModItems.SILVER_CHESTPLATE.get());
                    //output.accept(ModItems.SILVER_LEGGINGS.get());
                    //output.accept(ModItems.SILVER_BOOTS.get());
                    output.accept(ItemInit.SILVER_SWORD.get());
                    output.accept(ItemInit.SILVER_DAGGER.get());
                    output.accept(ItemInit.SILVER_MACE.get());
                    output.accept(ItemInit.SILVER_BOW.get());
                    output.accept(ItemInit.MOONSTONE_SHOVEL.get());
                    output.accept(ItemInit.MOONSTONE_PICKAXE.get());
                    output.accept(ItemInit.MOONSTONE_AXE.get());
                    output.accept(ItemInit.MOONSTONE_HOE.get());
                    output.accept(ItemInit.MOONSTONE_HELMET.get());
                    output.accept(ItemInit.MOONSTONE_CHESTPLATE.get());
                    output.accept(ItemInit.MOONSTONE_LEGGINGS.get());
                    output.accept(ItemInit.MOONSTONE_BOOTS.get());
                    output.accept(ItemInit.MOONSTONE_SWORD.get());
                    output.accept(ItemInit.MOONSTONE_DAGGER.get());
                    output.accept(ItemInit.MOONSTONE_MACE.get());
                    output.accept(ItemInit.MOONSTONE_BOW.get());
                    output.accept(ItemInit.DWARVEN_SHOVEL.get());
                    output.accept(ItemInit.DWARVEN_PICKAXE.get());
                    output.accept(ItemInit.DWARVEN_AXE.get());
                    output.accept(ItemInit.DWARVEN_HOE.get());
                    output.accept(ItemInit.DWARVEN_HELMET.get());
                    output.accept(ItemInit.DWARVEN_CHESTPLATE.get());
                    output.accept(ItemInit.DWARVEN_LEGGINGS.get());
                    output.accept(ItemInit.DWARVEN_BOOTS.get());
                    output.accept(ItemInit.DWARVEN_SWORD.get());
                    output.accept(ItemInit.DWARVEN_DAGGER.get());
                    output.accept(ItemInit.DWARVEN_MACE.get());
                    output.accept(ItemInit.DWARVEN_BOW.get());
                    output.accept(ItemInit.ORICHALCUM_SHOVEL.get());
                    output.accept(ItemInit.ORICHALCUM_PICKAXE.get());
                    output.accept(ItemInit.ORICHALCUM_AXE.get());
                    output.accept(ItemInit.ORICHALCUM_HOE.get());
                    output.accept(ItemInit.ORICHALCUM_HELMET.get());
                    output.accept(ItemInit.ORICHALCUM_CHESTPLATE.get());
                    output.accept(ItemInit.ORICHALCUM_LEGGINGS.get());
                    output.accept(ItemInit.ORICHALCUM_BOOTS.get());
                    output.accept(ItemInit.ORICHALCUM_SWORD.get());
                    output.accept(ItemInit.ORICHALCUM_DAGGER.get());
                    output.accept(ItemInit.ORICHALCUM_MACE.get());
                    output.accept(ItemInit.ORICHALCUM_BOW.get());
                    output.accept(ItemInit.MALACHITE_SHOVEL.get());
                    output.accept(ItemInit.MALACHITE_PICKAXE.get());
                    output.accept(ItemInit.MALACHITE_AXE.get());
                    output.accept(ItemInit.MALACHITE_HOE.get());
                    output.accept(ItemInit.MALACHITE_HELMET.get());
                    output.accept(ItemInit.MALACHITE_CHESTPLATE.get());
                    output.accept(ItemInit.MALACHITE_LEGGINGS.get());
                    output.accept(ItemInit.MALACHITE_BOOTS.get());
                    output.accept(ItemInit.MALACHITE_SWORD.get());
                    output.accept(ItemInit.MALACHITE_DAGGER.get());
                    output.accept(ItemInit.MALACHITE_MACE.get());
                    output.accept(ItemInit.MALACHITE_BOW.get());
                    output.accept(ItemInit.EBONY_SHOVEL.get());
                    output.accept(ItemInit.EBONY_PICKAXE.get());
                    output.accept(ItemInit.EBONY_AXE.get());
                    output.accept(ItemInit.EBONY_HOE.get());
                    output.accept(ItemInit.EBONY_HELMET.get());
                    output.accept(ItemInit.EBONY_CHESTPLATE.get());
                    output.accept(ItemInit.EBONY_LEGGINGS.get());
                    output.accept(ItemInit.EBONY_BOOTS.get());
                    output.accept(ItemInit.EBONY_SWORD.get());
                    output.accept(ItemInit.EBONY_DAGGER.get());
                    output.accept(ItemInit.EBONY_MACE.get());
                    output.accept(ItemInit.EBONY_BOW.get());
                    output.accept(ItemInit.DAEDRIC_SHOVEL.get());
                    output.accept(ItemInit.DAEDRIC_PICKAXE.get());
                    output.accept(ItemInit.DAEDRIC_AXE.get());
                    output.accept(ItemInit.DAEDRIC_HOE.get());
                    output.accept(ItemInit.DAEDRIC_HELMET.get());
                    output.accept(ItemInit.DAEDRIC_CHESTPLATE.get());
                    output.accept(ItemInit.DAEDRIC_LEGGINGS.get());
                    output.accept(ItemInit.DAEDRIC_BOOTS.get());
                    output.accept(ItemInit.DAEDRIC_SWORD.get());
                    output.accept(ItemInit.DAEDRIC_DAGGER.get());
                    output.accept(ItemInit.DAEDRIC_MACE.get());
                    output.accept(ItemInit.DAEDRIC_BOW.get());
                    output.accept(ItemInit.DRAGON_SHOVEL.get());
                    output.accept(ItemInit.DRAGON_PICKAXE.get());
                    output.accept(ItemInit.DRAGON_AXE.get());
                    output.accept(ItemInit.DRAGON_HOE.get());
                    output.accept(ItemInit.DRAGON_HELMET.get());
                    output.accept(ItemInit.DRAGON_CHESTPLATE.get());
                    output.accept(ItemInit.DRAGON_LEGGINGS.get());
                    output.accept(ItemInit.DRAGON_BOOTS.get());
                    output.accept(ItemInit.DRAGON_SWORD.get());
                    output.accept(ItemInit.DRAGON_DAGGER.get());
                    output.accept(ItemInit.DRAGON_MACE.get());
                    output.accept(ItemInit.DRAGON_BOW.get());

                });
                return builder.build();
            });


    public static void register(IEventBus eventBus) {
        CREATIVE_MODE_TABS.register(eventBus);
    }
}
